fullnameOverride: kube-logging


kibana:
  ingress:
    enabled: false
    host: ""
    ingressClassName: ""

elasticsearch:
  storage:
    size: 8Gi
    storageClassName: ""

  resources:
    limits:
      memory: 2Gi
      cpu: 1000m
    requests:
      memory: 1Gi
      cpu: 500m
