{{ if .Values.kibana.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kibana-ingress
  namespace: {{ .Release.Namespace }}
spec:
  ingressClassName: {{ .Values.kibana.ingressClassName }}
  rules:
  - host: {{ .Values.kibana.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kibana
            port:
              number: 5601
{{ end }}
